### ISSUE TITLE
Add "edit" contact button to account homepage

### ISSUE THREAD

**Issue by simonneb** [NeXt-Warning-System/xws-contact-web#5]
Alongside a remove button, add an edit button next to each location associated with the contact on the account page. 

Once clicked this opens a new edit page for that location. The user can:

- change the optional messages associated with that location. If location can only receive flood alert messages, do NOT allow the user to untick the box and instead offer to remove that location for their account
- remove the location entirely
- if a mobile number, they can select if they want the call via telephone or via text.

![Image of  screen](https://github.com/NeXt-Warning-System/documentation/blob/master/xws-contact-web/design/editpages.png?raw=true)

**Comment by davidjamesstone** [comment]
Edit location now complete. Will deploy on 28/07/20.
